import type { FontCategory } from "./types";

const FULL = [100, 200, 300, 400, 500, 600, 700, 800, 900] as const;
const STD = [300, 400, 500, 600, 700] as const;
const REG = [400, 700] as const;
const BOOK = [400, 500, 600, 700] as const;
const LIGHT = [300, 400, 700] as const;

export type CatalogSeed = readonly [
  family: string,
  category: FontCategory,
  weights: readonly number[],
  italic: boolean,
  variable: boolean,
  tags: readonly string[],
];

export const GOOGLE_FONT_SEEDS: readonly CatalogSeed[] = [
  ["Inter", "sans", FULL, true, true, ["neo-grotesque", "neutral", "ui"]],
  ["Roboto", "sans", FULL, true, false, ["neo-grotesque", "neutral"]],
  ["Open Sans", "sans", FULL, true, true, ["humanist", "neutral"]],
  ["Lato", "sans", FULL, true, false, ["humanist", "friendly"]],
  ["Montserrat", "sans", FULL, true, true, ["geometric", "display-sans"]],
  ["Poppins", "sans", FULL, true, false, ["geometric", "friendly"]],
  ["Source Sans 3", "sans", FULL, true, true, ["humanist", "editorial"]],
  ["Nunito", "sans", FULL, true, true, ["rounded", "friendly"]],
  ["Nunito Sans", "sans", FULL, true, true, ["rounded", "humanist"]],
  ["Work Sans", "sans", FULL, true, true, ["geometric", "neutral"]],
  ["Raleway", "sans", FULL, true, true, ["elegant", "display-sans"]],
  ["Outfit", "sans", FULL, false, true, ["geometric", "ui"]],
  ["DM Sans", "sans", STD, true, true, ["geometric", "ui"]],
  ["Plus Jakarta Sans", "sans", STD, true, true, ["geometric", "friendly"]],
  ["Manrope", "sans", STD, false, true, ["geometric", "ui"]],
  ["Figtree", "sans", STD, true, true, ["geometric", "ui"]],
  ["Karla", "sans", STD, true, true, ["grotesque"]],
  ["Mulish", "sans", FULL, true, true, ["humanist"]],
  ["Libre Franklin", "sans", FULL, true, true, ["humanist", "editorial"]],
  ["IBM Plex Sans", "sans", STD, true, false, ["grotesque", "technical"]],
  ["Space Grotesk", "sans", BOOK, false, true, ["geometric", "technical"]],
  ["Josefin Sans", "sans", STD, true, true, ["geometric"]],
  ["Oswald", "sans", STD, false, true, ["condensed", "display-sans"]],
  ["Barlow", "sans", FULL, true, false, ["grotesque", "condensed"]],
  ["Barlow Condensed", "sans", FULL, true, false, ["condensed"]],
  ["Archivo", "sans", FULL, true, true, ["grotesque"]],
  ["Archivo Narrow", "sans", REG, true, false, ["condensed"]],
  ["Rubik", "sans", STD, true, true, ["geometric", "friendly"]],
  ["Kanit", "sans", FULL, true, false, ["humanist"]],
  ["Titillium Web", "sans", LIGHT, true, false, ["humanist"]],
  ["Exo 2", "sans", FULL, true, true, ["geometric", "technical"]],
  ["Lexend", "sans", FULL, false, true, ["accessible", "humanist"]],
  ["Atkinson Hyperlegible", "sans", REG, true, false, ["accessible"]],
  ["Atkinson Hyperlegible Next", "sans", FULL, true, true, ["accessible"]],
  ["Public Sans", "sans", FULL, true, true, ["grotesque", "ui"]],
  ["Schibsted Grotesk", "sans", STD, true, true, ["grotesque"]],
  ["Sora", "sans", STD, false, true, ["geometric"]],
  ["Urbanist", "sans", FULL, true, true, ["geometric"]],
  ["Be Vietnam Pro", "sans", FULL, true, false, ["humanist"]],
  ["Noto Sans", "sans", FULL, true, true, ["noto", "humanist"]],
  ["Noto Serif", "serif", FULL, true, true, ["noto", "editorial"]],
  ["Noto Sans JP", "sans", FULL, false, true, ["noto"]],
  ["Noto Sans KR", "sans", FULL, false, true, ["noto"]],
  ["Noto Sans SC", "sans", FULL, false, true, ["noto"]],
  ["Noto Sans TC", "sans", FULL, false, true, ["noto"]],
  ["Noto Color Emoji", "display", [400], false, false, ["noto", "color", "emoji"]],
  ["Noto Emoji", "display", [400, 500, 600, 700], false, true, ["noto", "emoji"]],
  ["Nabla", "display", [400], false, true, ["color", "display"]],
  ["Bungee Spice", "display", [400], false, false, ["color", "display"]],
  ["Honk", "display", [400], false, true, ["color", "display"]],
  ["Kablammo", "display", [400], false, true, ["color", "display"]],
  ["Blaka Ink", "display", [400], false, false, ["color", "display"]],
  ["Playfair Display", "serif", STD, true, true, ["didone", "editorial"]],
  ["Merriweather", "serif", LIGHT, true, false, ["editorial"]],
  ["Lora", "serif", BOOK, true, true, ["editorial"]],
  ["Source Serif 4", "serif", FULL, true, true, ["editorial"]],
  ["Libre Baskerville", "serif", [400, 700], true, false, ["editorial"]],
  ["Cormorant Garamond", "serif", STD, true, false, ["editorial", "didone"]],
  ["EB Garamond", "serif", STD, true, true, ["editorial"]],
  ["Cormorant", "serif", STD, true, true, ["editorial"]],
  ["Fraunces", "serif", FULL, true, true, ["display", "editorial"]],
  ["Newsreader", "serif", STD, true, true, ["editorial"]],
  ["Instrument Serif", "serif", [400], true, false, ["editorial"]],
  ["DM Serif Display", "serif", [400], true, false, ["didone", "display"]],
  ["DM Serif Text", "serif", [400], true, false, ["didone"]],
  ["Bitter", "serif", FULL, true, true, ["slab"]],
  ["Roboto Slab", "serif", FULL, false, true, ["slab"]],
  ["Zilla Slab", "serif", LIGHT, true, false, ["slab"]],
  ["Arvo", "serif", REG, true, false, ["slab"]],
  ["IBM Plex Serif", "serif", STD, true, false, ["editorial", "technical"]],
  ["PT Serif", "serif", REG, true, false, ["editorial"]],
  ["Cardo", "serif", REG, true, false, ["editorial"]],
  ["Spectral", "serif", STD, true, false, ["editorial"]],
  ["Crimson Text", "serif", [400, 600, 700], true, false, ["editorial"]],
  ["Crimson Pro", "serif", FULL, true, true, ["editorial"]],
  ["Old Standard TT", "serif", REG, true, false, ["didone"]],
  ["Bodoni Moda", "serif", FULL, true, true, ["didone"]],
  ["Abril Fatface", "display", [400], false, false, ["didone", "display"]],
  ["Oswald", "sans", STD, false, true, ["condensed"]],
  ["Bebas Neue", "display", [400], false, false, ["condensed", "display"]],
  ["Anton", "display", [400], false, false, ["condensed", "display"]],
  ["Righteous", "display", [400], false, false, ["display"]],
  ["Pacifico", "handwriting", [400], false, false, ["script"]],
  ["Dancing Script", "handwriting", BOOK, false, true, ["script"]],
  ["Great Vibes", "handwriting", [400], false, false, ["script"]],
  ["Satisfy", "handwriting", [400], false, false, ["script"]],
  ["Caveat", "handwriting", BOOK, false, true, ["script"]],
  ["Patrick Hand", "handwriting", [400], false, false, ["script"]],
  ["Indie Flower", "handwriting", [400], false, false, ["script"]],
  ["Shadows Into Light", "handwriting", [400], false, false, ["script"]],
  ["Permanent Marker", "handwriting", [400], false, false, ["script"]],
  ["JetBrains Mono", "mono", STD, true, true, ["coding", "ligatures"]],
  ["Fira Code", "mono", LIGHT, false, true, ["coding", "ligatures"]],
  ["Source Code Pro", "mono", FULL, true, true, ["coding"]],
  ["IBM Plex Mono", "mono", STD, true, false, ["coding", "technical"]],
  ["Roboto Mono", "mono", STD, true, true, ["coding"]],
  ["Space Mono", "mono", REG, true, false, ["coding", "technical"]],
  ["Inconsolata", "mono", FULL, false, true, ["coding"]],
  ["Ubuntu Mono", "mono", REG, true, false, ["coding"]],
  ["Anonymous Pro", "mono", REG, true, false, ["coding"]],
  ["Cousine", "mono", REG, true, false, ["coding"]],
  ["Red Hat Mono", "mono", STD, true, true, ["coding"]],
  ["Geist Mono", "mono", FULL, false, true, ["coding"]],
  ["Instrument Sans", "sans", STD, true, true, ["grotesque", "ui"]],
  ["Manrope", "sans", STD, false, true, ["geometric"]],
  ["Monoton", "display", [400], false, false, ["display", "retro"]],
];
